### PR TITLE
Fixed versions of packages will not be updated

### PR DESCRIPTION
**Pull request by Gorniaky**

### CODE REVIEW

**Comment by Gorniaky** [comment]
sorry for previous PRs, i was testing git cli, now it's ok

**Comment by tylerlong** [comment]
Thanks for the PR.

Is [yarn upgrade](https://classic.yarnpkg.com/lang/en/docs/cli/upgrade/#toc-yarn-upgrade-package-latest-l-caret-tilde-exact-pattern) what you want? 

> The upgrade --latest command upgrades packages the same as the upgrade command, but ignores the version range specified in package.json. Instead, the version specified by the latest tag will be used (potentially upgrading the packages across major versions).

> The package.json file will be updated to reflect the latest version range. By default, the existing range specifier in package.json will be reused if it is one of: ^, ~, <=, >, or an exact version. Otherwise, it will be changed to a caret (^). One of the flags --caret, --tilde or --exact can be used to explicitly specify a range.

**Comment by tylerlong** [comment]
I've got your point, but it's a "breaking" change to this tool. Because by design, this tool is supposed to update packages to latest versions, regardless the versions specified in `package.json`. 

If you really want to ignore some packages, you may take advantages of the [ignore some packages](https://github.com/tylerlong/yarn-upgrade-all#ignore-some-packages) feature.

**Comment by Gorniaky** [comment]
> I've got your point, but it's a "breaking" change to this tool. Because by design, this tool is supposed to update packages to latest versions, regardless the versions specified in `package.json`.

oh ok ok, so I can make the filter activate with --ignore-exact-versions option?

**Pull request closed without merging**
